export const CHANGE_CATEGORY = "CHANGE_CATEGORY"
export const GET_CATEGORIES_SUCCES = "GET_CATEGORIES_SUCCES"
export const CHANGE_PRODUCT = "CHANGE_PRODUCT"
export const GET_PRODUCTS_SUCCES = "GET_PRODUCTS_SUCCES"
export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"

