export const CHANGE_CATEGORY = "CHANGE_CATEGORY"
export const GET_CATEGORIES_SUCCES = "GET_CATEGORIES_SUCCES"
export const CHANGE_PRODUCT = "CHANGE_PRODUCT"
export const GET_PRODUCTS_SUCCES = "GET_PRODUCTS_SUCCES"

